// <auto-generated />
using AplicacionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AplicacionApi.Migrations
{
    [DbContext(typeof(AseguradoraContext))]
    [Migration("20231017172728_firtsmigration")]
    partial class firtsmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AplicacionApi.Modelos.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Seguro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Codigo"));

                    b.Property<string>("ClienteCedula")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Prima")
                        .HasColumnType("real");

                    b.Property<float>("SumaAsegurada")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Seguro", b =>
                {
                    b.HasOne("AplicacionApi.Modelos.Cliente", null)
                        .WithMany("Seguros")
                        .HasForeignKey("ClienteCedula");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Cliente", b =>
                {
                    b.Navigation("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
