// <auto-generated />
using AplicacionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplicacionApi.Migrations
{
    [DbContext(typeof(AseguradoraContext))]
    partial class AseguradoraContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplicacionApi.Modelos.Cliente", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cedula");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Seguro", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("ClienteCedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Prima")
                        .HasColumnType("real");

                    b.Property<float>("SumaAsegurada")
                        .HasColumnType("real");

                    b.HasKey("Codigo");

                    b.HasIndex("ClienteCedula");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Seguro", b =>
                {
                    b.HasOne("AplicacionApi.Modelos.Cliente", null)
                        .WithMany("Seguros")
                        .HasForeignKey("ClienteCedula");
                });

            modelBuilder.Entity("AplicacionApi.Modelos.Cliente", b =>
                {
                    b.Navigation("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
